### ISSUE TITLE
bridger don't include the license file

### ISSUE THREAD

**Issue by puntogil** [dmlloyd/bridger#1]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
Thanks in advance
Regards

**Comment by dmlloyd** [comment]
Is Fedora actually packaging this?  It's a compile-time-only tool...

**Comment by puntogil** [comment]
is used in https://github.com/apache/groovy/blob/master/build.gradle#L212
I have no idea if this maven-plugin will be used to build groovy in Fedora
thanks for the fast reply

**Comment by dmlloyd** [comment]
Interesting.  They don't seem to be actually using it though.
